CREATE TABLE TABELLA(
CSAPATNEV VARCHAR2(25) PRIMARY KEY,
HELYEZES NUMBER (2),
CONSTRAINT TN CHECK (HELYEZES BETWEEN 1 AND 12),
LŐTTGÓL NUMBER (2),
KAPOTTGÓL NUMBER (2),
ELÉRTPONTOK NUMBER(3)
);

CREATE TABLE CSAPATOK(
KOLTSEGVETES NUMBER(7),
VÁROS VARCHAR2(20),
CSAPATNEV VARCHAR2(25) PRIMARY KEY,
FOREIGN KEY (CSAPATNEV) REFERENCES TABELLA (CSAPATNEV),
VÁRTHELYEZÉS NUMBER(2),
CONSTRAINT CV CHECK (VÁRTHELYEZÉS BETWEEN 1 AND 12)
);
CREATE TABLE GOLLOVOLISTA(
JATEKOSNEV VARCHAR2(20) PRIMARY KEY,
GÓLOK NUMBER(2),
ASSZISZTOK NUMBER(2),
CSAPATNEV VARCHAR2(25),
FOREIGN KEY (CSAPATNEV) REFERENCES CSAPATOK (CSAPATNEV)
);
